services:
  postgres:
    image: postgres:17
    container_name: spring_htmx_test_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: spring_htmx_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5435:5432"
    volumes:
      - spring_htmx_test_pgdata:/var/lib/postgresql/data

volumes:
  spring_htmx_test_pgdata:
